### ISSUE TITLE
Test Suite

### ISSUE THREAD

**Issue by mjachi** [METHODS-Group/DRDMannTurb#44]
We should include tests for basic functionality for

- [x] Generated wind should be div-free. Refer to Section V.B in Keith et al.
- [x] Check symmetries in the eddy lifetime function (evenness wrt Cartesian coordinates)
- [x] Parameter setting/ interface initialization**
- [x] Data Generation
- [x] GPU allocation (as of writing, GPU load is consistently 95%+ throughout training past initialization). Related tests to perf should serve as mandatory regression tests. 

**We already have some tests for this by @alizma; this item exists since presumably it is not complete and perhaps more should be written.

**Comment by alizma** [comment]
On the topic of perf tests, the quantity of interest is GPU utilization during training, which is currently a consistent >95% as of the first release. I added a crude test to check utilization immediately after the training loop completes. The resulting perf statistics are accurate since the sample period refreshes only once per second using ``torch.cuda.utilization()``, so the utilization reflects the tail end of training. However, the proper way of doing this would be to introduce a mock of the training loop that tracks GPU utilization during each Wolfe iteration, which can be done with TB utilities. Though this might seem necessary for completeness, it would be more effort than necessary to accomplish the goal since perf regression would definitely break the crude way of testing. So I'll consider the crude way of doing this sufficient for the purpose of these tests, unless it's critical to get iteration-wise granularity on GPU utilization...
